name: xiv
description: Window to Eorzea
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  responsive_widgets: ^2.0.1
  provider: ^4.1.3
  progress_indicators: ^0.1.5
  show_up_animation: ^1.0.2
  flip_card: ^0.4.4
  flutter_launcher_icons: ^0.7.5
  adaptive_theme: ^0.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/stickers/
#  - assets/companion
#  - assets/misc

  fonts:
    - family: FFFonts
      fonts:
        - asset: assets/font/FFFonts.ttf