name: xiv
description: Window to Eorzea
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  assets:
#  - assets/icons
#  - assets/companion
#  - assets/misc

  fonts:
    - family:  FFFonts
      fonts:
        - asset: assets/font/FFFonts.ttf
